version: "3.3"
services:
  client:
    build:
      context: ./client/
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        SERVER_PORT: ${SERVER_PORT}
        SERVER_PROTOCOL: ${SERVER_PROTOCOL}
        SERVER_URL: ${SERVER_URL}
    ports:
      - ${EXPOSED_CLIENT_PORT}:${CLIENT_PORT}
    command: serve -s build -p ${CLIENT_PORT}

  server:
    build: 
      context: ./server/flask_service
    ports:
      - ${EXPOSED_SERVER_PORT}:${SERVER_PORT}
    command: python app.py