version: "3.3"
services:
  client:
    build: 
      context: ./client/
      args:
        CLIENT_PORT: 3000
        SERVER_PORT: 5000
    ports:
      - 3000:3000
    command: serve -s build -p 3000
  server:
    build: 
      context: ./server/flask_service
      args:
        SERVER_PORT: 5000
    ports:
      - 5000:5000
    command: python app.py